### PR TITLE
Improve performance for loading DatasetV2, and add threshold parameter

### PR DESCRIPTION
**Pull request by shuw**
Adding a threshold parameter allows the caller to only keep part of the dataset in memory, and speed up loading.

With these changes, load time goes from ~10seconds => ~5 seconds. And if you set a threshold of 0.01, it goes down to ~2 seconds.

The performance gains come from reducing the number of large dictionary operations. And of course, with a threshold applied, also reduces the number of rows processed.

### CODE REVIEW

**Comment by philipperemy** [comment]
@shuw thanks a lot for your PR!
Can you make sure the build runs fine?
https://github.com/philipperemy/name-dataset/runs/3617653214?check_suite_focus=true
Just a linter problem. 

```
./names_dataset/nd_v2.py:41:5: E303 too many blank lines (2)
```

Thank you!

**Comment by shuw** [comment]
Fixed it :)

**Comment by philipperemy** [comment]
@shuw thank you! merged!

**Comment by philipperemy** [comment]
Released in 2.1.0!

**Pull request merged**
